### ISSUE TITLE
The docs are not describing that the software is a DynDNS alike CLIENT..

### ISSUE THREAD

**Issue by elico** [TimothyYe/godns#10]
The docs are not describing that the software is a DynDNSalike CLIENT.. and not a DynDNS alike service..
Can you please add a note about it in the README.md and also that it will be reflected in the godoc?

**Comment by TimothyYe** [comment]
OK.

**Comment by elico** [comment]
@TimothyYe Thanks!
Do you know of any DynDNS open service?
I might be able to compile a document and a server for this.

**Comment by TimothyYe** [comment]
@elico There is also a free DynDNS service: [HE.net](https://dns.he.net), I already refactored GoDNS to support it. You may refer to the branch: he.  I plan to merge it to master branch tomorrow.

**Comment by TimothyYe** [comment]
@elico Already merged, V1.3 released.
