### ISSUE TITLE
DO NOT UPDATE MAIN DOMAIN

### ISSUE THREAD

**Issue by dreamer2q** [TimothyYe/godns#106]
Please do not update **MAIN** domain, only sub domains can be updated.

Please at least, offer your sincerely user an option to close this **FEATURE**,

In my case, I have multi-wan, targeted different ips, with net1, net2, net3 ... as the subdomains,
I run multi-instances, each of them handles only one local interface.

But, it smartly updates the MAIN domain related with its subdomain. This is NOT what I wanted.

**Comment by dreamer2q** [comment]
![image](https://user-images.githubusercontent.com/56211747/112762257-49bf4080-9031-11eb-875d-12d5860b7e82.png)

THIS MAKES THINGS WORSE.

**Comment by dreamer2q** [comment]
ROOT DOMAIN IS NOT WHAT I NEEDED

**Comment by TimothyYe** [comment]
Hmmmmmm, some users require to update the root domain record, but some users don't want it.
https://github.com/TimothyYe/godns/issues/76

It's a bit hard to balance it.
I think I can provide a more elegant to support both.

**Comment by dreamer2q** [comment]
@TimothyYe  I do really appreciate your good working.

I think an option in the config file should really help solve this problems.

By default, this feature should not be enabled, in order to be compatible with old versions.

**Comment by TimothyYe** [comment]
There is going to be a new release tonight to fix this issue.

**Comment by TimothyYe** [comment]
This issue has been fixed by V2.3.4 (https://github.com/TimothyYe/godns/releases/tag/V2.3.4)
I'll close it.
