### ISSUE TITLE
DNSPOD限制每小时3600个请求，导致系统无法使用了

### ISSUE THREAD

**Issue by zsinba** [TimothyYe/godns#113]
**Describe the bug**  

**The frequency of this issue**  
- [ ] This issue is easy to reproduce.
- [ ] This issue is not easy to reproduce.

**Steps to Reproduce**  
Steps to reproduce the behavior.

**Your GoDNS configuration**  
Past your GoDNS configuration here, please remember to remove the sensitive information.

**Expected behavior**  

**Screenshots**  

**Environment (please complete the following information):**  
 - DNS Provider: [e.g. Cloudflare]
 - OS: [e.g. Linux]

**Additional context**

**Comment by TimothyYe** [comment]
配置文件里面有 "interval": 300
默认5分钟循环一次，你现在配置的多少？

**Comment by zsinba** [comment]
默认是五分钟,不也就是300s吗, 配置的300不就是五分钟吗.

我之前 尝试修改为10,20,100,120,300,600. 都是返回错误,跟DNSPOD的官方沟通,说是超限的原因

可能原因是我的域名下面二级域名比较多修改,所以就超限了.

**Comment by TimothyYe** [comment]
你配置了多少个二级域名？

**Comment by zsinba** [comment]
三十个左右吧。

**Comment by TimothyYe** [comment]
按30个二级域名来算，interval 配置成5分钟一次，如果GoDNS第一次启动，每5分钟就会轮询一遍域名和所有子域名，第一次执行更新所有二级域名，这样粗略估计下来一个小时总API调用次数就是 (1+30+30) * 12 = 732 也没达到3600次。

你是不是在一个小时内多次启动了程序，所以才会超？

**Comment by zsinba** [comment]
我在NAS开了一个Docker ，在虚拟机开了一个服务。 是两个godns在跑。 

如果设置的不是5分钟，是30秒。 也就是每小时120，一天是2880次， 这离的是比较近了。

这样来看，问题就找到了。

有什么建议吗？

**Comment by TimothyYe** [comment]
你的使用场景是什么？
为啥要跑两个godns? 另外，为啥要配置30个二级域名呢？

**Comment by TimothyYe** [comment]
如果DNSPod有API调用次数限制的话，可以试试其他的DNS解析服务商

**Comment by zsinba** [comment]
多谢你的回复， 我换阿里云的DNS了。

**Comment by LiCijun** [comment]
> 如果DNSPod有API调用次数限制的话，可以试试其他的DNS解析服务商
最好是应用程序检测到ip地址没有变更的情况下，就不提交到后台。这样就大大减少了调用次数。
