### ISSUE TITLE
是否可以加入 freebsd 支持

### ISSUE THREAD

**Issue by littlesum** [TimothyYe/godns#114]
` extracting github.com/sirupsen/logrus v1.8.1
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: extracting github.com/miekg/dns v1.1.29
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: extracting golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: extracting golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: extracting golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
# golang.org/x/sys/unix
../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/syscall_freebsd_amd64.go:56:1: error: redefinition of ‘Syscall9’
   56 | func Syscall9(num, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, err syscall.Errno)
      | ^
../go/pkg/mod/golang.org/x/sys@v0.0.0-20200625212154-ddb9806d33ae/unix/gccgo.go:42:1: note: previous definition of ‘Syscall9’ was here
   42 | func Syscall9(trap, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, err syscall.Errno) {
      | ^`

我自己编译过不去，应该是没有添加freebsd的支持

**Comment by TimothyYe** [comment]
我在MacOS下交叉编译没报错

```
CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build
```
