### ISSUE TITLE
在修改（并非添加）DNS记录时，Alidns提示DNS已存在

### ISSUE THREAD

**Issue by zsinba** [TimothyYe/godns#115]
**Describe the bug**  

**The frequency of this issue**  
- [ X] This issue is easy to reproduce.
- [ ] This issue is not easy to reproduce.

**Steps to Reproduce**  
Steps to reproduce the behavior.

**Your GoDNS configuration**  
Past your GoDNS configuration here, please remember to remove the sensitive information.

**Expected behavior**  

**Screenshots**  

**Environment (please complete the following information):**  
 - DNS Provider: [e.g. Cloudflare] aliyun  alidns
 - OS: [e.g. Linux] linux  
 - 

**Additional context**  

UpdateDomainRecord error.status 400, Error:{"RequestId":"C43F763B-0D91-4012-9A70-67248452C25A","HostId":"alidns.aliyuncs.com","Code":"DomainRecordDuplicate","Message":"The DNS record already exists.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=DomainRecordDuplicate&source=PopGw"}

有一批nds修改，但是部分会提示如上所示。

**Comment by TimothyYe** [comment]
你好，域名是你先手动添加到阿里云的吗？
之前也有人提这样的issue，但是我这边没重现，能不能说一下你重现的具体步骤？
