### ISSUE TITLE
Dry Run

### ISSUE THREAD

**Issue by benvcutilli** [TimothyYe/godns#118]
Hi, I was wondering if we could get a dry run feature to make sure that GoDNS is actually gonna work when the IP address changes. Many dynamic IPs don't change for months. However, maybe "dry run" isn't the best name: ideally, I think GoDNS should have a feature to force an IP update, even if the IP address hasn't changed; again, this would be for testing purposes.

Thanks!

**Comment by TimothyYe** [comment]
Sorry for the late reply, thanks for your suggestion, the `dry run` can be included in the next release.

**Comment by Kirbstomper** [comment]
I can take a look at this.

**Comment by TimothyYe** [comment]
@Kirbstomper Thanks

**Comment by TimothyYe** [comment]
It is already implemented by the `run_once` setting: https://github.com/TimothyYe/godns#manually
