### ISSUE TITLE
Allows update of private IP range

### ISSUE THREAD

**Issue by tomcollis** [TimothyYe/godns#119]
The default (or example) URLs for getting your external IPv4 and IPv6 addresses are currently not working due to an expired certificate. I've changed mine to:

ipv4.icanhazip.com
ipv6.icanhazip.com

Both the URLs above can be accessed over HTTP or HTTPS, they are supported by CloudFlare so should be very reliable.

Anyway, the problem this caused was every 10 minutes (the interval for my GoDNS), the following would happen:

1 - GoDNS checks IP address, fails to get current WAN address so uses the address on the local interface (docker 172.000.000.000)
2 - Checks the current DNS record, which is different to the address from step 1
3 - Tries to update CloudFlare via API to an IP address classed as internal (which thankfully fails because CloudFlare won't allow it)

This process repeats forever.

It would be great if GoDNS recognises an IPv4 or IPv6 an internal address and don't try to update and sends a different message via notifications (I'm currently using Telegram).

I think this is part bug and part enhancement.

Tom

**Comment by TimothyYe** [comment]
Thanks Tom, sorry for the late reply. 

I've updated the default URL for getting IPV4 and IPV6 addresses.

For the bug you mentioned about, if the GoDNS fails to get WAN address, should output the error message, and wait until the next loop. I'm not sure how it gets the private IP from the local interface? Did you enable the `ip_interface` feature and configure the interface name?
