### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by LiCijun** [TimothyYe/godns#122]
更新IP的时候，如果遇到网络不通，将需要十多分钟，才会超时错误退出，导致下次更新的时候，相差时间过大。

**Comment by LiCijun** [comment]
![godns](https://user-images.githubusercontent.com/1553523/140504548-2c0ebf41-eae6-432b-b876-5e02e576df11.jpg)
Duplicate of #

**Comment by LiCijun** [comment]
测试出现此问题 可以将防火墙设为DROP

**Comment by TimothyYe** [comment]
知道为啥了，因为默认超时的时间很长，我会加一个默认的超时时间

**Comment by LiCijun** [comment]
临时采用了  PPPOE拨号成功后 重启godns 暂时先解决了这个问题

**Comment by TimothyYe** [comment]
https://github.com/TimothyYe/godns/commit/dc0c1bf6f5662d3d38dcacc9138c27659b931e9d
改动在这里
