### ISSUE TITLE
this select block is useless since panicChan is not buffered, please remove it.

### ISSUE THREAD

**Issue by georgetso** [TimothyYe/godns#13]
https://github.com/TimothyYe/godns/blob/d3f82cffe63c759f4da7ca3a0749126d552cdc15/godns.go#L64

**Comment by TimothyYe** [comment]
@georgetso I'm also thinking about to remove panicCount, panicChan and related codes. If panic occurs, just let the program exit, since upstart/systemd/docker will restart it automatically.

**Comment by TimothyYe** [comment]
removed.
