### ISSUE TITLE
Avoid too much api call times by creating a file to store last IP address.

### ISSUE THREAD

**Issue by ddbullfrog** [TimothyYe/godns#14]
Hi @TimothyYe,

I've like to provide the following suggestion.

After getting current IP address every time,
if the current IP == IP in the file, 
    do nothing 
otherwise
    replace the IP in the file with the current IP and then continue the existing logic.

Thanks,
Dong

**Comment by TimothyYe** [comment]
@ddbullfrog Thanks, it's a good idea. I'll refactor this part later.

**Comment by TimothyYe** [comment]
Hi @ddbullfrog 
This feature has already been implemented and will be available in next release: V1.4.
