### ISSUE TITLE
建议更换默认获取IP接口

### ISSUE THREAD

**Issue by del-xiong** [TimothyYe/godns#140]
停止工作发现是获取IP被ip.sb拉黑了(频率不高5分钟一次，果然够sb)
换成了https://api.ipify.org/

**Comment by del-xiong** [comment]
测了下发现是因为ipsb禁止了无ua的请求，可以考虑加上ua
不过感觉既然是api那就不应该做这种限制

**Comment by TimothyYe** [comment]
谢谢你的建议，空了我改一下把请求的ua加上，另外，再多放几个备用的API在README或者sample config里面

**Comment by del-xiong** [comment]
好的
