### ISSUE TITLE
How can i set max size of log file?

### ISSUE THREAD

**Issue by hkuuki** [TimothyYe/godns#15]
Plat:Windows 10
Ran godns.exe at background for 2 week, and got 20GB log file.

**Comment by TimothyYe** [comment]
OMG~
I ran it on my Gen8 Server for about 1 week, from 2018/01/30 11:43:00 to 2018/02/05 13:59:00, the size of godns.log is:

```bash
λ timothy [~] → du -sh godns.log
568K    godns.log
```

**Comment by hkuuki** [comment]
Yeah, i know.
i think the reason is i'm still using dialup via system instead router to connect to ISP, which was unstable.
Maybe when i lost internet connection, godns could log massive error. 
Unfortunately, i just delete the file, don't saw what was happened.

**Comment by TimothyYe** [comment]
I can refactor the logging mechanism in the later releases and then the user can set max log size via the config options.

**Comment by TimothyYe** [comment]
For V1.5, log only outputs to stdout, so I may close this issue.
