### ISSUE TITLE
AliDns : The parameter is invalid

### ISSUE THREAD

**Issue by caijingwen-vincent** [TimothyYe/godns#150]
**Describe the bug**  
1. configure the configuration file
2. run godns.exe
3. get the error : The parameter value Value is invalid.

**The frequency of this issue**  
- [ ] This issue is easy to reproduce.

**Your GoDNS configuration**  
{
  "provider": "AliDNS",
  "email": "REPLACE_ME_ACCESS_KEY",
  "password": "REPLACE_ME_ACCESS_TOKEN",
  "login_token": "",
  "domains": [{
      "domain_name": "***.com.cn",
      "sub_domains" : ["www"]
    }
  ],
  "resolver": "2001:4860:4860::8888",
  "ipv6_url": "",
  "ip_type": "IPv6",
  "ip_url": "",
  "interval": 10,
  "socks5_proxy": ""
}

**Expected behavior**  
update ali dns correct

**Screenshots**  
run exe file result: 
![image](https://user-images.githubusercontent.com/71600126/165951583-35673264-fe3f-45de-8439-4a5a2399467c.png)
ali probleck check result:
![image](https://user-images.githubusercontent.com/71600126/165951710-6392add5-4b4a-4944-bb36-8384bf0f43aa.png)

**Environment (please complete the following information):**  
 - DNS Provider: [e.g. AliDns]
 - OS: [Windows]

**Comment by caijingwen-vincent** [comment]
I open the debug level ; and I found that my ip printed as null . maybe there is the question.
I use the ipv6 mode;
![image](https://user-images.githubusercontent.com/71600126/165956188-2844b759-9492-4261-8c48-e53ee124ce16.png)

**Comment by caijingwen-vincent** [comment]
When I change the configuration properties from  "ipv6_url": ""  to    : "ipv6_url": "http://api-ipv6.ip.sb/ip"
The debug log shows my ipv6 address ,and then update correct ; 
![image](https://user-images.githubusercontent.com/71600126/165957432-6b24731d-ed24-46dd-8786-3572b82e2dba.png)


so the README.md says below may wrong ?:
![image](https://user-images.githubusercontent.com/71600126/165957373-a7c7a655-692a-408a-801d-64ba4ca707f8.png)

**Comment by TimothyYe** [comment]
Thanks for your feedback and it is good to hear that you've figured out the problem.
