### ISSUE TITLE
DuckDNS IPv6 NXDOMAIN error

### ISSUE THREAD

**Issue by GitThisAcc** [TimothyYe/godns#152]
**Describe the bug**  
GoDNS won't update my IPv6.
Error NXDOMAIN

**Log**
```
godns.exe
level=info msg="GoDNS started, entering main loop..."
level=info msg="Creating DNS handler with provider: DuckDNS"
level=debug msg="currentIP is:MYIPv6"
level=error msg=NXDOMAIN
```

**Steps to Reproduce** 

Use `DuckDNS` subdomain and update `IPv6` via GoDNS.

**Your GoDNS configuration**  
```
{
    "provider": "DuckDNS",
    "password": "",
    "login_token": "TOKEN",
    "domains": [
        {
            "domain_name": "duckdns.org",
            "sub_domains": [
                "SUBDOMAIN"
            ]
        }
    ],
    "ipv6_url": "https://api-ipv6.ip.sb/ip",
    "ip_type": "IPv6",
    "interval": 300,
    "resolver": "2606:4700:4700::1111",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36",
    "use_proxy": false,
    "debug_info": true,
    "run_once": true,
    "notify": {
        "telegram": {
            "enabled": true,
            "bot_api_key": "APIKEY",
            "chat_id": "CHATID",
            "message_template": "GoDNS Service:%0ADomain {{ .Domain }} is updated to%0A{{ .CurrentIP }}",
            "use_proxy": false
        }
    }
}
```

**Expected behavior** 
Last week it worked without issue, but today I could not get to update my IPv6 via GoDNS.

**Environment:**  
 - DNS Provider: `DuckDNS`
 - OS: Windows 10 Pro, via command-line and/or as a service.

**Additional context**  
I can still update via https manually:
https://www.duckdns.org/update?domains=SUBDOMAIN&token=TOKEN&ipv6=MYIPV6&verbose=true
I changed to different ipv6_url and cloudflare resolver, and two different subdomains. Always *error msg=NXDOMAIN*

Thank you!

**Comment by TimothyYe** [comment]
@ThisIsCyreX Thanks, I was trying to reproduce this issue. So there is no need to update the code?
