### ISSUE TITLE
Question: Does GoDNS watch config file changes?

### ISSUE THREAD

**Issue by shizunge** [TimothyYe/godns#164]
Does GoDNS watch config file changes?

Or it just loads the config file at beginning once?

**Comment by TimothyYe** [comment]
Currently, it just loads the config file once when it starts. However, I have a plan to make it watch the changes and reload the configurations at the runtime. This feature may be delivered in the future.

**Comment by TimothyYe** [comment]
This feature is supported by the latest release.
