### ISSUE TITLE
[feature] Create subdomains on Cloudflare

### ISSUE THREAD

**Issue by WesleyBatista** [TimothyYe/godns#167]
For Linode provider we seem to support auto creation of subdomain if it does not exist ([mentioned in the docs](https://github.com/TimothyYe/godns/blob/001bb15b783b6abfcd929d415035bb13befae3d5/README.md?plain=1#L525) and [implemented here](https://github.com/TimothyYe/godns/blob/001bb15b783b6abfcd929d415035bb13befae3d5/internal/provider/linode/provider.go#L27-L51)), however for Cloudflare I currently get:
```
level=error msg=NXDOMAIN
```

Error goes away once I manually create the `A` record from `Cloudflare > DNS` UI, but I would like to manage everything as code.
Would be cool having the same behavior as for Linode for Cloudflare as well.

It would also be nice to have the non-existent subdomain in the error message so it saves one round of checking back in the code/configs which subdomain failed.

> _As side note, thanks for this amazing tool :heart:_

**Comment by TimothyYe** [comment]
Thanks for the suggestion, the providers are implemented by different contributors, so the behaviors may be different from each other. 

I'll look into the API docs of Cloudflare and try to create the subdomains instead of throwing out the errors.

**Comment by WesleyBatista** [comment]
Thanks a lot for implementing so fast! Works from my side :sparkles: 

However, it creates the record with proxying disabled (I see it's the default when calling the [API](https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record)), thus the IP gets exposed, and I am still required going to the Cloudflare UI to enable record by record. It would be awesome if we had the option to instruct `"proxied":true`
