### ISSUE TITLE
no log? I start the docker and nothing happen.

### ISSUE THREAD

**Issue by AtwindYu** [TimothyYe/godns#17]
I check the log file :/var/lib/docker/containers/a9572ee726a5ca500857f03eae9a9078df707f164457006d0e9accca5c6da776/a9572ee726a5ca500857f03eae9a9078df707f164457006d0e9accca5c6da776-json.log

and there is nothing.

**Comment by TimothyYe** [comment]
Maybe log file is generated in the docker container...
Please refer to #16, I plan to use stdout instead of the log file in the next release.

**Comment by TimothyYe** [comment]
V1.5 is released, now stdout is the default log output.
You can use `docker logs` to get it.

Please refer to https://github.com/TimothyYe/godns/releases/tag/V1.5
