### ISSUE TITLE
Option to enable `proxied` for Cloudflare provider

### ISSUE THREAD

**Issue by WesleyBatista** [TimothyYe/godns#175]
Thanks a lot for implementing so fast! Works from my side :sparkles: 

However, it creates the record with proxying disabled (I see it's the default when calling the [API](https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record)), thus the IP gets exposed, and I am still required going to the Cloudflare UI to enable record by record. It would be awesome if we had the option to instruct `"proxied":true`

_Originally posted by @WesleyBatista in https://github.com/TimothyYe/godns/issues/167#issuecomment-1205836275_

**Comment by TimothyYe** [comment]
Good suggestion! This feature is also covered by the release `v2.8.8`.

**Comment by WesleyBatista** [comment]
This works from my side :heavy_check_mark:
