### ISSUE TITLE
ip_url 接口如果通过代理后会是代理的IP

### ISSUE THREAD

**Issue by FisherJoey** [TimothyYe/godns#178]
ip_url 接口如果通过代理后会是代理的IP

这个有办法解决吗？

**Comment by TimothyYe** [comment]
能展开讲讲吗？

**Comment by FisherJoey** [comment]
我今天更新到最新版本后。（Docker）
https://api.ipify.org/
https://myip.biturl.top/
https://ip4.seeip.org/
https://ipecho.net/plain
https://api-ipv4.ip.sb/ip
这几个IP取得的IP地址全是我上网的代理IP。（我还没有使用全局代理，只是用白名单。）
路由器上的实际公网IP并没有取得。

当我关掉代理后，就能在Docker中取得实际的IP了。也就是路由器上的公网IP。

**Comment by TimothyYe** [comment]
如果你单独设置了一层全局代理，Docker是没法感知到的，除非把docker的IP白名单不走代理

**Comment by FisherJoey** [comment]
> 如果你单独设置了一层全局代理，Docker是没法感知到的，除非把docker的IP白名单不走代理

嗯。目前是这么解决的。
