### ISSUE TITLE
我发现取IP的API有的时候会失败。

### ISSUE THREAD

**Issue by FisherMS** [TimothyYe/godns#181]
![image](https://user-images.githubusercontent.com/12068896/185734723-4b72a1e4-03fd-4599-8b45-2de34e931883.png)

能加上多个备选的取IP API吗？
这样一个不行换一个。

**Comment by TimothyYe** [comment]
这个也可以有

**Comment by TimothyYe** [comment]
其实这个要看一下是因为网络不稳定，还是真的是获取公网IP的URL不稳定。如果是本地网络不稳定，这个for循环遍历一遍所有的URL也会失败。

**Comment by FisherMS** [comment]
是的。我发现，有些时候没有连上互连网，请求再多，也没用。
另外，我用2.8.9 发现全部请求都失败了。2.8.8是没有问题的。奇怪了！

**Comment by TimothyYe** [comment]
因为获取ip那里有个bug，我改好了，重新发布2.8.9
