### ISSUE TITLE
use -c instead of -v with command line

### ISSUE THREAD

**Issue by UniqueUserajs** [TimothyYe/godns#182]
**Describe the bug**  
The docker example in README.md has the wrong option to indicate 

**The frequency of this issue**  
- [*] This issue is easy to reproduce.
- [ ] This issue is not easy to reproduce.

**Steps to Reproduce**  
docker run \
-d --name godns --restart=always \
-v /path/to/config.json:/config.json \
timothyye/godns:latest

**Your GoDNS configuration**  
N/A

**Expected behavior**  
should not produce an error

**Screenshots**  
N/A

**Environment (please complete the following information):**  
 N/A

**Additional context**  
N/A

**Comment by TimothyYe** [comment]
Actually, the `-v` is an option provided by docker, it is used to mount the target path to the docker container.

**Comment by TimothyYe** [comment]
This command with `-v` option will mount the config file from your local disk to the container's target path `/config.json`.

And the executable file `godns` is also placed at the root directory of the container, by default, it tries to load the config file from the same directory, so `/config.json` will be loaded.
