### ISSUE TITLE
Config compatibility issue: "ip_url" in old config vs. "ip_urls" in new config

### ISSUE THREAD

**Issue by adam-ah** [TimothyYe/godns#189]
**Describe the bug**  
In older configs `ip_url` was a single item. In newer configs, it is now an array and called `ip_urls`.
When upgrading `go_dns` to a new version, the `ip_url` seems to be ignored, leading to guessing the public ip, and not updating anything.
Even the `debug` log does not contain any information about silently failing (log from v2.8.9)

```
INFO[0000] GoDNS started, entering main loop...
INFO[0000] Creating DNS handler with provider: Cloudflare
DEBU[0000] IP () matches cached IP (), skipping
```

**The frequency of this issue**  
- [*] This issue is easy to reproduce.

**Steps to Reproduce**  
Get `v2.7.1` and `v2.8.9`

Create a `config.json` with the following line:
```
...
  "ip_url": "https://api.ipify.org",
...
```

The old version will work as expected, producing a log something like this:
```
INFO[0000] GoDNS started, entering main loop...
INFO[0000] Creating DNS handler with provider:Cloudflare
INFO[0000] Checking IP for domain x.com
INFO[0001] Querying records with type:A
 NFO[0001] IP mismatch: Current(xxx) vs Cloudflare(xxx)
INFO[0001] Record updated: x.com - xxx
```

The new version will ignore `ip_url` and will produce the log *as above*.

**Expected behavior**  
The new version should either 
- [PREFERRED] work as expected and be backward compatible
- [NOT PREFERRED] fail, saying it is now called `ip_urls` and should be an array

**Environment (please complete the following information):**  
 - DNS Provider:  Cloudflare
 - OS: linux

**Comment by TimothyYe** [comment]
Yes, for `v2.8.9`, it is a breaking change, the `ip_url` is changed to `ip_urls`.
I've menntioned it in the release notes of `v2.8.9`

https://github.com/TimothyYe/godns/releases/tag/v2.8.9

**Comment by adam-ah** [comment]
I appreciate you documented it, @TimothyYe . 

At the same time, software vendors / developers can safely rely on people *not* reading standard release notes. 

Most people (you and I included) run services and tools on the 100s scale, and these pieces of software get updated regularly, sometimes daily. Just think of the usual `apt upgrade`. It is not feasible (nor required) to keep up to date on standard release notes for all these software. 

Yet, I cannot remember an `apt upgrade` suddenly breaking something on my system, let alone breaking quietly, like this change did (stops working without any warnings / errors).

Overall, this breaking change introduced should have been avoided, as both parameters (array and single string) can be easily supported. 

I recommend two things:
- Avoid breaking changes at all costs going forward
- Fix this one so this remains backward compatible (I'm happy to open a PR)

Thoughts?

**Comment by TimothyYe** [comment]
@adam-ah OK, it sounds reasonable, I'll release a new version to make it backward compatible with the `ip_url` config option.

**Comment by TimothyYe** [comment]
The new version `v2.9.0` has fixed it.

**Comment by adam-ah** [comment]
This is great work, thank you. I added a few stylistic comments to your change, for you to consider.

**Comment by TimothyYe** [comment]
Thanks, will make some updates later.
