### ISSUE TITLE
Feature request: Support OVH provider

### ISSUE THREAD

**Issue by Nicryc** [TimothyYe/godns#191]
It would be cool to support OVH too as a dynamic DNS provider. I'm not an expert at all but I think it's possible since other tools specifically made for OVH exist on GitHub.

**Comment by TimothyYe** [comment]
Thanks for the advice, I'll consider this proposal.

**Comment by Phiwatec** [comment]
I added the functionality. @Nicryc can you test it with one of your domains?
I did a test with one of mine and it worked. Still would be good to get feedback from other users.
