### ISSUE TITLE
Prebuilt binary for OpenBSD, please. This rc syntax should suffice for creation of an rc file to run with rc.d. 

### ISSUE THREAD

**Issue by anoduck** [TimothyYe/godns#194]
Wanting to use godns on the server for my website, and was disappointed with the limitations faced by users of OpenBSD. It would be nice if a prebuilt binary for OpenBSD was not available. If forced with the only option being to build a binary from the repo, it would be beneficial if the makefile provided a means to install the freshly built binary, even if that installation targeted the users `$GOBIN` folder.

Once an OpenBSD user has produced the binary, he is then limited as to how the binary is converted into a working system daemon. Although, not tested yet, the below rc file should allow an OpenBSD user to run godns as a system daemon managed by rc. Before doing so, the user will have to create a folder to place the configuration file into `/etc/godns` and create a system user to run the process as `_godns`.

```rc
#!/bin/ksh

daemon="/usr/local/bin/godns"
daemon_flags="--config /etc/godns/config.yaml"
daemon_user="_godns"
daemon_timeout=60

. /etc/rc.d/rc.subr

rc_stop_signal=INT

rc_cmd $1
```

**Comment by TimothyYe** [comment]
Hello, I can try to create the build for OpenBSD, but I don't have the OpenBSD environment to verify it...

**Comment by anoduck** [comment]
I would be willing to verify that it works, if that is possible. OpenBSD is my daily driver.

My rc file snippet did not work... :( ... So, I will need to work out the kink before it is usable. 

Right now it is working well with a simple `nohup ./godns -f godns.yml &`

**Comment by TimothyYe** [comment]
@anoduck you could try with this temp release: https://github.com/TimothyYe/godns/releases/tag/v2.9.2-1

**Comment by anoduck** [comment]
@TimothyYe Is there supposed to be a build for OpenBSD in the release?

Regardless, I built one on my machine: [godns_2.9.2-1_OpenBSD_x86_64.tar.gz](https://github.com/TimothyYe/godns/files/10449087/godns_2.9.2-1_OpenBSD_x86_64.tar.gz)

It is currently running the dynamic dns for my live server.

**Comment by TimothyYe** [comment]
@anoduck Yes, pls help to check this release
![image](https://user-images.githubusercontent.com/860685/213359911-e3ecc538-5680-40db-b6b5-d6fe6efe8427.png)

Try to download the release which is suitable for your machine and run the program.

**Comment by TimothyYe** [comment]
@anoduck I got one FreeBSD VPS and verified it, it works.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/860685/213480401-55701975-0008-47cc-bf7d-ae75631bb7d3.png">

**Comment by anoduck** [comment]
Like butter and garlic. Shazam!

**Comment by anoduck** [comment]
The different projects have diverged independently of each other and not binary interchangeable. At one time, FreeBSD and Darwin/macOS were nearly identical, but not any longer. OpenBSD and NetBSD share a lot of codebase, and still work with each other to resolve issues, but the two projects have different goals and move in different directions.

**Comment by TimothyYe** [comment]
I see, thanks for the explanation.
