### ISSUE TITLE
Deleting published tags is a bad idea

### ISSUE THREAD

**Issue by linyinfeng** [TimothyYe/godns#196]
**Describe the bug**

The tag `2.9.2-1` and its release was deleted. It's a bad idea to delete published tags.
I think that all published tags should not be deleted anymore.

**Expected behavior**

After a release getting published, its tag should not be deleted or altered, because other projects may refer to the commit of the release using the tag.

Deleting tag can cause real problems. For example, <https://github.com/NixOS/nixpkgs/pull/211540#issuecomment-1397193824>. 

**Screenshots**

2023-01-19 19:21 UTC+8, the release and its tag was still there.
![photo_2023-01-19_23-56-50](https://user-images.githubusercontent.com/11229748/213495345-63d12f77-ee0a-43d7-89b9-87508bee7cac.jpg)

2023-01-20 00:19 UTC+8, the release and its tag is missing.
![image](https://user-images.githubusercontent.com/11229748/213495989-0a0abc3a-eaae-4d3c-9685-a347e8a6386d.png)

**Comment by TimothyYe** [comment]
Sorry, let me re-create the release `2.9.2-1`
