### ISSUE TITLE
Usage of ip_urls should use round-robin

### ISSUE THREAD

**Issue by diizzyy** [TimothyYe/godns#198]
Unless I'm reading the code incorrectly there doesn't seem to be any kind of load balancing going on when defining multiple ip_urls. That would probably be a good idea to implement for reliability and to be "a good netizen" instead of hammering one single service.

**Comment by TimothyYe** [comment]
It's a good idea, but now I'm busy with my master's courses, I may have time to implement this feature in May.

**Comment by TimothyYe** [comment]
This feature is already included in the release v3.0.1
