### ISSUE TITLE
yaml config file support in docker?

### ISSUE THREAD

**Issue by kngharv** [TimothyYe/godns#199]
Is config in yaml format supported in the docker image?

The reason I am asking this is that 

`godns -c ~/config.yaml `

everything is fine.

When I switched to docker image,  pass the config file in the "docker run" command with 
`"-v /home/user/docker/godns/config.yaml:/config.yaml" `

I go the error in the log:

Error occurs while reading config file, please make sure config file exists!
`time="2023-00-00T00:00:00Z" level=fatal msg="open ./config.json: no such file or directory"`

Does it mean that for docker image, only json config format is supported?  

Thanks in advance

**Comment by TimothyYe** [comment]
Oh, this might be an issue, I'll check it.

**Comment by TimothyYe** [comment]
@kngharv The release `v2.9.8` fixes this problem: https://github.com/TimothyYe/godns/releases/tag/v2.9.8

While running GoDNS with a YAML config file, an extra environment is needed, for example:

```bash
docker run \
-d --name godns \
-e CONFIG=/config.yaml \
--restart=always \
-v /path/to/config.yaml:/config.yaml \
timothyye/godns:latest
```

The environment `CONFIG` is the path of the `config.yaml` which is mounted into the docker container.
