### ISSUE TITLE
 ip比较错误

### ISSUE THREAD

**Issue by richardxyz** [TimothyYe/godns#20]
dnspod_handler.go中用strings.Contains会出问题的
// Continue to check the IP of sub-domain
				if len(ip) > 0 && !strings.Contains(currentIP, ip) {
例:currentIp=192.168.100.234,ip=192.168.100.2

**Comment by TimothyYe** [comment]
谢谢，此issue已修复，请更新最新版本：https://github.com/TimothyYe/godns/releases/tag/V1.5.1
