### ISSUE TITLE
how to hidden cmd window in widnows 

### ISSUE THREAD

**Issue by zyc63959** [TimothyYe/godns#208]
when it run , every time there is cmd window in windows ,how to hidden it

**Comment by TimothyYe** [comment]
https://github.com/TimothyYe/godns#as-a-windows-service

You may try to run it as a Windows service.

**Comment by zyc63959** [comment]
thanks. but i wouldn't like to use NSSM that it is not friendly to me . could you add a funciton to hidden cmd windows ?

**Comment by TimothyYe** [comment]
You may also try with:

Create a shortcut: Create a shortcut for the command-line program and modify the shortcut properties to run the program in a hidden window. Right-click on the shortcut, select "Properties," go to the "Shortcut" tab, and choose "Run: Minimized" or "Run: Hidden" in the "Run" dropdown menu.
