### ISSUE TITLE
网络访问失败时需要添加延时再重试  目前连续访问会导致CPU占用100%

### ISSUE THREAD

**Issue by LiCijun** [TimothyYe/godns#217]
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \" dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"h\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"0\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[7408]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \"\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"
Oct 13 17:34:28 R86S godns[1370]: time="2023-10-13T17:34:28+08:00" level=error msg="Cannot get IP:Get \\": dial tcp [2001:19f0:6001:407a:5400:2ff:fefc:dcad]:10080: connect: network is unreachable"

**Comment by TimothyYe** [comment]
感谢，我会尽快修复

**Comment by TimothyYe** [comment]
v3.0.2已经修复
