### ISSUE TITLE
想用网卡的IP地址报错

### ISSUE THREAD

**Issue by LiCijun** [TimothyYe/godns#220]
设置为 "ipv6_urls": [ "" ], 错误如下：
Oct 28 17:15:49 R86S godns[1922806]: time="2023-10-28T17:15:49+08:00" level=error msg="Cannot get IP:Get \"\": unsupported protocol scheme \"\""
Oct 28 17:15:49 R86S godns[1922806]: time="2023-10-28T17:15:49+08:00" level=error msg="Cannot get IP:Get \"\": unsupported protocol scheme \"\""
Oct 28 17:15:49 R86S godns[1922808]: time="2023-10-28T17:15:49+08:00" level=error msg="Cannot get IP:Get \"\": unsupported protocol scheme \"\""
设置为 "ipv6_urls": [  ], 或删除时  错误如下：
Oct 28 17:15:50 R86S godns[1923070]: panic: runtime error: integer divide by zero
Oct 28 17:15:50 R86S godns[1923070]: goroutine 19 [running]:
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/pkg/lib.(*IPHelper).getNext(...)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/pkg/lib/ip_helper.go:81
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/pkg/lib.(*IPHelper).getIPOnline(0xc000180410)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/pkg/lib/ip_helper.go:174 +0x5ed
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/pkg/lib.(*IPHelper).getCurrentIP(0xc000180410)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/pkg/lib/ip_helper.go:146 +0x48
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/pkg/lib.(*IPHelper).GetCurrentIP(0xc000180410)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/pkg/lib/ip_helper.go:63 +0x35
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/internal/handler.(*Handler).UpdateIP(0xc0001a5a40, 0x0?)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/internal/handler/handler.go:70 +0x33
Oct 28 17:15:50 R86S godns[1923070]: github.com/TimothyYe/godns/internal/handler.(*Handler).LoopUpdateIP(0xc0001a5a40, {0xb4cd50, 0xc000180460}, 0x0?)
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/internal/handler/handler.go:47 +0x67
Oct 28 17:15:50 R86S godns[1923070]: created by github.com/TimothyYe/godns/internal/manager.(*DNSManager).Run in goroutine 1
Oct 28 17:15:50 R86S godns[1923070]:         godns-3.0.2/internal/manager/dns_manager.go:56 +0x207
Oct 28 17:15:50 R86S systemd[1]: godns@godns6.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by TimothyYe** [comment]
3.0.2确实有这个问题，已经在最新版修复了
