### ISSUE TITLE
DNSPod无法更新解析

### ISSUE THREAD

**Issue by psdty** [TimothyYe/godns#25]
你好，进程启动后DNSPOD无法更新A记录
请帮忙看看是哪里问题呢？非常感谢！
【GoDNS】2018/07/31 15:00:22 debug: 0 www
【GoDNS】2018/07/31 15:00:22 get_subdomain:status code: 10001
【GoDNS】2018/07/31 15:00:22 domain: www.pipiv.com subDomainID:  ip: 
【GoDNS】2018/07/31 15:00:22 debug: 0 test
【GoDNS】2018/07/31 15:00:22 get_subdomain:status code: 10001
【GoDNS】2018/07/31 15:00:22 domain: test.pipiv.com subDomainID:  ip: 
【GoDNS】2018/07/31 15:00:22 Going to sleep, will start next checking in 5 minutes...
【GoDNS】2018/07/31 15:05:22 Checking IP for domain pipiv.com 
【GoDNS】2018/07/31 15:05:22 get_domain:status code: 10001
【GoDNS】2018/07/31 15:05:23 currentIP is: 47.52.71.33

【GoDNS】2018/07/31 15:05:23 debug: 0 www
【GoDNS】2018/07/31 15:05:23 get_subdomain:status code: 10001
【GoDNS】2018/07/31 15:05:23 domain: www.pipiv.com subDomainID:  ip: 
【GoDNS】2018/07/31 15:05:23 debug: 0 test
【GoDNS】2018/07/31 15:05:23 get_subdomain:status code: 10001
【GoDNS】2018/07/31 15:05:23 domain: test.pipiv.com subDomainID:  ip: 
【GoDNS】2018/07/31 15:05:23 Going to sleep, will start next checking in 5 minutes...
【GoDNS】2018/07/31 15:10:23 Checking IP for domain pipiv.com 
【GoDNS】2018/07/31 15:10:23 get_domain:status code: 10001
【GoDNS】2018/07/31 15:10:25 currentIP is: 47.52.71.33

**Comment by TimothyYe** [comment]
get_subdomain:status code: 10001

好象是获取子域名出错

**Comment by TimothyYe** [comment]
应该不是，检查一下配置文件？

**Comment by psdty** [comment]
我的配置config.json文件如下：
{
  "provider": "DNSPod",
  "email": "psdty@163.com",
  "password": "*******",
  "login_token": "5e9d9d8694354232*************",
  "domains": [
    {
      "domain_name": "apipiv.com",
      "sub_domains": [
        "www",
        "test"
      ]
    }
  ],
  "ip_url": "http://members.3322.org/dyndns/getip",
  "socks5_proxy": "",
  "notify": {
    "enabled": false,
    "smtp_server": "",
    "smtp_username": "",
    "smtp_password": "",
    "smtp_port": 25,
    "send_to": ""
  }
}

**Comment by psdty** [comment]
有加的哦
![qq 20180808141256](https://user-images.githubusercontent.com/2361932/43819363-38e6c6e8-9b15-11e8-88ef-4ff084b729c5.png)

**Comment by TimothyYe** [comment]
或者你先试试用用户名和密码的方式？

**Comment by psdty** [comment]
请问用用户名和密码方式是指什么呢？

**Comment by TimothyYe** [comment]
就是把填入DNSPod的账号：email, password，不用token的方式

**Comment by psdty** [comment]
不填token的话报这个

【GoDNS】2018/08/11 14:23:38 debug: 0 www
【GoDNS】2018/08/11 14:23:38 get_subdomain:status code: 8
【GoDNS】2018/08/11 14:23:38 domain: www.pipiv.com subDomainID:  ip: 
【GoDNS】2018/08/11 14:23:38 debug: 0 test
【GoDNS】2018/08/11 14:23:38 get_subdomain:status code: 8
【GoDNS】2018/08/11 14:23:38 domain: test.pipiv.com subDomainID:  ip: 
【GoDNS】2018/08/11 14:23:38 Going to sleep, will start next checking in 5 minutes...

**Comment by key4j** [comment]
@psdty @TimothyYe 应该是最近DNSPOD关闭了邮箱+密码的登录，必须使用token来授权，“完整的API Token 是由 ID,Token 组合而成的，用英文的逗号分割”，我之前也是只用了token一直失败

**Comment by TimothyYe** [comment]
@key4j  谢谢，我去研究研究

**Comment by TimothyYe** [comment]
@psdty @key4j  看了一下API文档，说旧的用户名和密码的方式依然支持

@psdty  你可以试试这个文章上提到的，用 ID,token 的方式

**Comment by key4j** [comment]
@TimothyYe 官方文档确实是说支持用户名和密码（很久没更新了），但是我以前一直用的官方提供的客户端，只支持用户名和密码的，上周开始不能正常登录了。然后我测试godns的配置，**确实只有token配置为ID,token的方式才能正常解析**，否则token配置错误提示status为1001，只配置用户名和密码提示status为8.

**Comment by TimothyYe** [comment]
@key4j 谢谢你的反馈，明天我编译一个版本在VPS上试试

**Comment by TimothyYe** [comment]
@psdty 试过了，用户名密码确实返回错误， id,token的方法可行。
@key4j 谢谢。

**Comment by psdty** [comment]
非常感谢 @TimothyYe @key4j
我这边测试也正常了。
