### ISSUE TITLE
树莓派无法安装

### ISSUE THREAD

**Issue by nicky1605** [TimothyYe/godns#27]
作者您好，您提供的都是X64的，我看到您写了支持树莓派，但是我的树莓派是32位的，无法使用。使用go语言的话不知道为什么也不能编译，正常的X64的CentOS 7 的系统可以编译

**Comment by TimothyYe** [comment]
release新增了一个arm 32位版本(godns-arm-1.6.tar.gz)，你试试?https://github.com/TimothyYe/godns/releases/tag/V1.6

**Comment by TimothyYe** [comment]
@nicky1605 
Go编译arm 64位版本：
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build

Go编译arm 32位版本：
CGO_ENABLED=0 GOOS=linux GOARCH=arm go build

**Comment by nicky1605** [comment]
> release新增了一个arm 32位版本(godns-arm-1.6.tar.gz)，你试试?https://github.com/TimothyYe/godns/releases/tag/V1.6

谢谢。arm 32位的可以用了。您发的那个Go编译的我就没试了。
昨天我编译的时候直接用的以下命令编译的，编译完没有看到任何文件。
```
sudo apt-get install golang
sudo env GOPATH=/home/pi/Downloads/godns go get -v  github.com/timothyye/godns
sudo env GOPATH=/home/pi/Downloads/godns go build  github.com/timothyye/godns
```
总之现在可以用了。谢谢！
