### ISSUE TITLE
why display Error occurs while unmarshal config file?

### ISSUE THREAD

**Issue by poppy7921** [TimothyYe/godns#28]
GoDNS V1.6
Error occurs while unmarshal config file, please make sure config file correct!
invalid character '"' after object key:value pair
--------config.json---------
{
  "provider": "Cloudflare",
  "email": "xxxx@gmail.com"
  "password": "xxxx261db6a66eff0f9ca8ee94c86e78dxxxx",
  "domains": [{
      "domain_name": "xxxx.net",
      "sub_domains": ["my"]
    }],
  "ip_url": "https://ifconfig.co/ip",
  "socks5_proxy": ""
}

**Comment by TimothyYe** [comment]
"email": "xxxx@gmail.com"
should be 
"email": "xxxx@gmail.com",

**Comment by thank243** [comment]
> "email": "[xxxx@gmail.com](mailto:xxxx@gmail.com)"
> should be
> "email": "[xxxx@gmail.com](mailto:xxxx@gmail.com)",

It seem that the example is missed the ",".

**Comment by TimothyYe** [comment]
Updated, thanks!
