### ISSUE TITLE
能否增加Alidns的支持？

### ISSUE THREAD

**Issue by xiongbao** [TimothyYe/godns#30]
现在大部分用户都考虑使用Alidns，稳定，速度快。
请支持一下Alidns吧

**Comment by TimothyYe** [comment]
主要我没有域名放阿里上，所以还没试过

**Comment by TimothyYe** [comment]
最近已经开始支持这个功能了

**Comment by TimothyYe** [comment]
@xiongbao  AliDNS 已经支持，请下载 https://github.com/TimothyYe/godns/releases/tag/V1.7 并参考项目README中的配置
