### ISSUE TITLE
只想更新子域名，但是主域名也被更新了

### ISSUE THREAD

**Issue by thank243** [TimothyYe/godns#32]
只想更新yy.xxx.com域名的ip。结果连xxx.com的ip也一起更新了。

**Comment by TimothyYe** [comment]
能否看看你的配置文件？

**Comment by thank243** [comment]
{
  "provider": "Cloudflare",
  "email": "you@example.com",
  "password": "Global API Key",
  "domains": [{
      "domain_name": "xxx.com",
      "sub_domains": ["yy"]
    }
  ],
  "ip_url": "https://ifconfig.co/ip"
}

**Comment by thank243** [comment]
"domain_name": "xxx.com",如果改成"domain_name": "yy.xxx.com", 系统报错

**Comment by TimothyYe** [comment]
大概知道原因了

**Comment by thank243** [comment]
是小弟配置问题么？

**Comment by TimothyYe** [comment]
https://github.com/TimothyYe/godns/releases/tag/V1.6.2

刚发布了一个版本，试试这个

**Comment by thank243** [comment]
子域名可以了，但是如果我想更新主域名应怎么填写？

**Comment by TimothyYe** [comment]
本来是设计成只更新子域名的，主域名，可以考虑在子域名里面加入'www'

**Comment by thank243** [comment]
好的，我还以为加上@参数就能更新xxx.com这个域名。

**Comment by TimothyYe** [comment]
这个功能还没实现，哈哈

**Comment by thank243** [comment]
哈哈，上个版本直接同时更新xxx.com和yy.xxx.com我还以为已经实现了呢。

**Comment by TimothyYe** [comment]
那是个bug
