### ISSUE TITLE
didnt updated domain - Cloudflare

### ISSUE THREAD

**Issue by Excel1** [TimothyYe/godns#33]
GoDNS works correctly on subdomains like "www" or "test". But it seems to be that only subdomains got updated. Domains like "example.com" got ignored. (Only tested by using Cloudflare)

**Comment by Thor77** [comment]
This "bug" was introduced with 0fdb8af7277d0c85efcab3f551fa8b9f475951d0.
Was there a reason for this @TimothyYe?

**Comment by TimothyYe** [comment]
Hi @Excel1 & @Thor77 
Actually, GoDNS is only designed for updating subdomains, there is another issue also mentioned about this https://github.com/TimothyYe/godns/issues/32

And the existing handlers `DNSPod Handler` & `HE Handler` they both are implemented as `only update subdomains` to make all these handlers have the same behavior, I just updated the `Cloudflare Handler` yesterday.

**Comment by TimothyYe** [comment]
@Excel1 There is a way to solve this problem. If you want not just subdomains are updated but also the domain itself, you can use the previously released version like https://github.com/TimothyYe/godns/releases/tag/V1.6.1

**Comment by Excel1** [comment]
@TimothyYe Maybe you can create an option in the config file to turn it on or off

**Comment by TimothyYe** [comment]
Good suggestion!  I'll consider to add it, thanks!

**Comment by fabianskibr** [comment]
Is this not working for cloudflare?
The exemple.com domain is ignored and your ip is not being updated.

```
[GoDNS] 2019/07/24 12:27:22 GoDNS started, entering main loop...
[GoDNS] 2019/07/24 12:27:23 Creating DNS handler with provider: Cloudflare
[GoDNS] 2019/07/24 12:27:24 Current IP is: 123.123.123.123
[GoDNS] 2019/07/24 12:27:24 Checking IP for domain example.com
[GoDNS] 2019/07/24 12:27:39 Skiping record: example.com
[GoDNS] 2019/07/24 12:27:39 Going to sleep, will start next checking in 300 seconds...
```

I'm using version 1.8

**Comment by fabianskibr** [comment]
my config.json

```
{
  "provider": "Cloudflare",
  "email": "myemail@gmail.com",
  "password": "786dasdasdas8d9as798s7s8cxz8x8xx",
  "domains": [{
      "domain_name": "example.com"
    }
  ],
  "ip_url": "https://myip.biturl.top",
  "interval": 300,
  "socks5_proxy": ""
}
```

**Comment by TimothyYe** [comment]
Currently only supports to update subdomains.

**Comment by fabianskibr** [comment]
I understand. however Do you have any plans to add duckdns support?
The current options are very good and stable, but have a slightly high dns propagation time.

**Comment by TimothyYe** [comment]
@fabianskibr Do you mean https://www.duckdns.org?

**Comment by fabianskibr** [comment]
Yes, exactly

**Comment by TimothyYe** [comment]
Checked, it is possible to support.

**Comment by fabianskibr** [comment]
would be great

**Comment by TimothyYe** [comment]
When it is completed, I will notify you.

**Comment by fabianskibr** [comment]
ok thanks i will test

**Comment by TimothyYe** [comment]
@fabianskibr , GoDNS V1.9 is released to support DuckDNS, you may try it: https://github.com/TimothyYe/godns/releases/tag/V1.9

**Comment by fabianskibr** [comment]
> @fabianskibr, GoDNS V1.9 is released to support DuckDNS, you may try it: https://github.com/TimothyYe/godns/releases/tag/V1.9

Seems not working for windows, godns.exe executable doesn't open
I just added my token and my subdomain (it's only numbers)

my config:

```
{
  "provider": "DuckDNS",
  "password": "",
  "login_token": "123123123132132",
  "domains": [
    {
      "domain_name": "www.duckdns.org",
      "sub_domains": [
        "84714641"
      ]
    }
  ],
  "ip_url": "https://icanhazip.com",
  "interval": 30,
  "socks5_proxy": "",
}
```

I tried too

```
      "domain_name": "duckdns.org",
      "sub_domains": [
        "84714641"
       ]
```

and 

```
      "domain_name": "84714641.duckdns.org",
      "sub_domains": [
        ""
       ]
```

**Comment by fabianskibr** [comment]
It's working on linux, I just have to remove the comma at the end of this line:

`"socks5_proxy": "",`

I realize that it always updates the ip even if there are no changes, is that how it should work anyway?

**Comment by TimothyYe** [comment]
@fabianskibr README already updated, the comma is removed.
It is suggested to set the `interval` as 300 seconds.

And the released is also updated, please download the latest version.
It will not always update the IP unless it is changed.

**Comment by fabianskibr** [comment]
Everything works now, great!

**Comment by TimothyYe** [comment]
@fabianskibr Thanks!
