### ISSUE TITLE
Use half-width brackets in log

### ISSUE THREAD

**Issue by mbyzhang** [TimothyYe/godns#35]
Hi, @TimothyYe 

Please use half-width brackets instead of full-width ones in log, since some systems may have problems rendering full-width brackets. Thanks.

**Comment by mbyzhang** [comment]
```
【GoDNS】2019/01/31 03:08:38 GoDNS started, entering main loop...
【GoDNS】2019/01/31 03:08:38 Creating DNS handler with provider: Cloudflare
【GoDNS】2019/01/31 03:08:38 Current IP is: xxx.xxx.xxx.xxx
【GoDNS】2019/01/31 03:08:38 Checking IP for domain sub.example.com
```

**Comment by TimothyYe** [comment]
Do you mean the brackets `【` and `】`?

**Comment by mbyzhang** [comment]
Yes

**Comment by TimothyYe** [comment]
OK, I'll update it.

**Comment by TimothyYe** [comment]
Done.

@mbyzhang  Please try the latest release: https://github.com/TimothyYe/godns/releases/tag/V1.7.1
