### ISSUE TITLE
Add check ip duration to settings will be good!

### ISSUE THREAD

**Issue by tinysnake** [TimothyYe/godns#36]
Hi, Some ip address provider will ban you if you from asking the ip too frequently. so add a duration setting instead of fixed 5 minutes will be better.
Thanks!

**Comment by TimothyYe** [comment]
@tinysnake Done, please download V1.7.2
https://github.com/TimothyYe/godns/releases/tag/V1.7.2

**Comment by tinysnake** [comment]
magnificent!

**Comment by TimothyYe** [comment]
@tinysnake Please also note the config file change, a new field `interval` is added.

**Comment by tinysnake** [comment]
thx, nice work again!
