### ISSUE TITLE
Support Google domains

### ISSUE THREAD

**Issue by gedw99** [TimothyYe/godns#37]
Console is here:
https://domains.google.com

Help explaining how to support it is here:
https://support.google.com/domains/answer/6147083

This walks through the code:
https://medium.com/@jeremygale/how-to-set-up-a-free-dynamic-hostname-with-ssl-cert-using-google-domains-58929fdfbb7a

If you stub in the code I can help test it as i use them

**Comment by TimothyYe** [comment]
Hi @gedw99, I'll start to work on this enhancement, but for now `China` is not supported by Google domains.
So I need your help to test it when this feature is available, thanks!

**Comment by TimothyYe** [comment]
Hi @gedw99, there is an RC release for supporting Google domains, if you have time, please help to test it, thanks a lot!
https://github.com/TimothyYe/godns/releases/tag/RC1.8
