### ISSUE TITLE
Recommended to support ipv6

### ISSUE THREAD

**Issue by xingsiyue** [TimothyYe/godns#39]

**Comment by SadPencil** [comment]
Personally,

* IPv6 needs AAAA record to be configured. Some DDNS providers don't even provide such an interface to update AAAA records.
* Your computer obtains more than one IPv6 addresses from the router. Typically, one from SLAAC and one from DHCPv6 (stateful). Whether updating either one of these addresses, or updating all the addresses to the domain, needs discussion. Besides, most DDNS providers don't support multiple AAAA records.
* If your router supports IPv6, it is most probably that you are using a ASUS router or a OpenWRT router, which contains the DDNS update scripts. Most routers from China don't support IPv6. As of writing, MIIT - CHINA just announced the list of recommended IPv6 routers.

In my opinion, maybe this enhancement is worth thinking at the end of 2020.

**Comment by cklx0719** [comment]
那么，现在是不是应该到了考虑IPV6的时候了？

阿里/HE我自己验证是可以通过API更新AAAA记录的了。
对于每个设备都有IPV6地址且会自动变更的国内环境来讲，DDNS显得非常重要啊

**Comment by SadPencil** [comment]
> 
> 
> 那么，现在是不是应该到了考虑IPV6的时候了？
> 
> 阿里/HE我自己验证是可以通过API更新AAAA记录的了。
> 对于每个设备都有IPV6地址且会自动变更的国内环境来讲，DDNS显得非常重要啊

同意你的观点，但是这个项目的代码可能要为此进行一次重构。等作者 @TimothyYe 回复吧。

**Comment by TimothyYe** [comment]
不知道现在IPV6的普及程度怎么样了？我在新加坡，试了自己家里的宽带，是支持IPV6的，但是公司的网络好像又不行。

@cklx0719 @SadPencil 你们能否帮测试一下国内网络的支持情况？ https://test-ipv6.com/

**Comment by cklx0719** [comment]
现在国内的电信宽带，基本都开通了IPV6，我在广东，光猫设置更改一下，都可以获取到IPV6地址。技术公司的网络更是必须配置IPV6了，高校之类的更早普及的就更不用说了。
我使用这个DDNS就是在家里客厅放了台小服务器，电信封了IPV4 IP的80端口，但IPV6 IP的端口全部是开放的。

**Comment by SadPencil** [comment]
> 
> 
> 不知道现在IPV6的普及程度怎么样了？我在新加坡，试了自己家里的宽带，是支持IPV6的，但是公司的网络好像又不行。
> 
> @cklx0719 @SadPencil 你们能否帮测试一下国内网络的支持情况？ https://test-ipv6.com/

你的思路不是很好。在我给 GoDNS 添加“从网卡直接获取IP地址”的特性之前，GoDNS完全依赖网上的服务去获取IP。而需要用DDNS的，都是有公网IP的人，从网上服务获取IP会因为运营商NAT线路问题获取到错误的IP地址。在IPv6时代，每个设备都有自己的公网可访问IP地址，DDNS的单位也从路由器变成了设备。直接从网卡获取IPv6地址是主要功能，而从网上服务获取IP沦为辅助。因此IPv6网络是否拿满分，是否能访问互联网，对 DDNS 来说意义不是很大。
当然，工信部早就强制推行了IPv6。我在2018年夏天就发现有IPv6了，/56的公网，也能拿到满分。

**Comment by TimothyYe** [comment]
```
在我给 GoDNS 添加“从网卡直接获取IP地址”的特性之前，GoDNS完全依赖网上的服务去获取IP。
```
我之前用成都电信，也是有公网IP，不过公网IP并不是绑定在上网的电脑上，而是光猫拨号之后分配到的公网IP。运行在电脑上的程序没法直接通过“从网卡直接获取IP”的方式拿到公网IP，所以才有了以来网上的服务去拿公网IP的设计。

**Comment by SadPencil** [comment]
可以理解。IPv6没有NAT，无论光猫是路由模式还是桥接模式，底下的设备依然可以获得公网IPv6地址，所以以从网卡获取为主，网络服务为辅。
