### ISSUE TITLE
New Cloudflare API Token

### ISSUE THREAD

**Issue by thiagotalma** [TimothyYe/godns#41]
It would be great if Cloudflare's new authentication was implemented using tokens, which have granular access control.

API Tokens use the standard Authorization: Bearer header for authentication instead of `x-auth-email` and `x-auth-key` that API Keys use. Requests can be authenticated like the following:

```shell
curl -X GET "https://api.cloudflare.com/client/v4/zones/cd7d0123e3012345da9420df9514dad0" \ 
-H "Content-Type:application/json" \ 
-H "Authorization: Bearer 1234567893feefc5f0q5000bfo0c38d90bbeb"```

**Comment by TimothyYe** [comment]
Thanks will put this in next iteration.

**Comment by TimothyYe** [comment]
@thiagotalma Please refer to this release: https://github.com/TimothyYe/godns/releases/tag/V1.9.4

**Comment by thiagotalma** [comment]
Thanks!
