### ISSUE TITLE
cloudflare 不会更新主域名

### ISSUE THREAD

**Issue by jarvanh** [TimothyYe/godns#43]
cloudflare貌似只能更新子域名

**Comment by TimothyYe** [comment]
现在默认只支持子域名更新，主域名更新会考虑后续支持

**Comment by jarvanh** [comment]
个人感觉支持主域名还是有必要的，可以考虑使用@或者留空来配置主域名

**Comment by TimothyYe** [comment]
之前设计考虑到更新二级域名，DNS刷新时间会很快。往往更新主域名，等待DNS刷新的时间会更长，并不是很合适用主域名来作为DDNS。
