### ISSUE TITLE
Google Domains support

### ISSUE THREAD

**Issue by jfritz** [TimothyYe/godns#45]
`CheckSettings()` in `utils.go` doesn't seem to do validation check if service is "Google". 

As a result, any google config will return the error at the bottom of the if block, resulting in the "Settings is invalid!  please provide supported DNS provider: DNSPod/HE/AliDNS/Cloudflare/GoogleDomain/DuckDNS" error.

Using latest 1.9 release.

My config.json:

```
{
  "provider": "Google",
  "email": "CENSORED",
  "password": "CENSORED",
  "domains": [{
      "domain_name": "CENSORED.net",
      "sub_domains": ["www","test"]
  }],
  "ip_url": "https://myip.biturl.top",
  "interval": 300,
  "socks5_proxy": ""
}
```

**Comment by TimothyYe** [comment]
@jfritz  Thanks! It's a bug, I'll fix it.

**Comment by TimothyYe** [comment]
@jfritz https://github.com/TimothyYe/godns/releases/tag/V1.9.1 
Please try the latest version.

**Comment by jfritz** [comment]
Thanks, this gets my config running.
