### ISSUE TITLE
第二次执行提示这个属于正常吗

### ISSUE THREAD

**Issue by chenxianqi** [TimothyYe/godns#47]
UpdateDomainRecord error.Status 400, Error:{"RequestId":"8DDD65EF-500D-49FA-8418-CC6016AEC07A","HostId":"alidns.aliyuncs.com","Code":"DomainRecordDuplicate","Message":"The DNS record already exists."}
当前应该是尝试添加了一次吧，而没有去判断这个解释是否存在，存在去修改，不存在去添加新

**Comment by chenxianqi** [comment]
或者就是修改如果相同，阿里返回的错误信息，改一下提示吧，No need to update

**Comment by TimothyYe** [comment]
谢谢，我看看

**Comment by TimothyYe** [comment]
@chenxianqi 之前没有域名托管在阿里云，最近新买了一个，仿佛并没有重现？你是手动添加了一次域名再运行程序？
