### ISSUE TITLE
有考虑添加AAAA解析吗

### ISSUE THREAD

**Issue by MasterOfStar** [TimothyYe/godns#50]
打算把ipv6解析出去做DDNS，找了一圈都没找到多少支持windows的

**Comment by TimothyYe** [comment]
@MasterOfStar 你的域名用的哪家的服务商？

**Comment by MasterOfStar** [comment]
CF

**Comment by TimothyYe** [comment]
@MasterOfStar 我得看一下API如何集成先

**Comment by TimothyYe** [comment]
@MasterOfStar  我会先考虑实现CF的IPV6功能

**Comment by TimothyYe** [comment]
@MasterOfStar  CF的IPv6已经支持了，参考: https://github.com/TimothyYe/godns/releases/tag/V1.9.5
