### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by rdricco** [TimothyYe/godns#54]
I'm getting this error when trying to use on a raspberry 4 docker:

````
standard_init_linux.go:211: exec user process caused "exec format error"
````

I'm new on docker, any idea about this issue? I've tried the docker command from docs.

**Comment by TimothyYe** [comment]
@rdricco Sorry for the late reply.
I forgot to build the docker image for the ARM architecture, now the images are updated, you may delete the old docker image and try again.
