### ISSUE TITLE
telegram notifying sometimes with empty value 

### ISSUE THREAD

**Issue by khorsmann** [TimothyYe/godns#65]
I got regularly telegram notifications with an empty string for the ip via telegram. 
Should be checked before notification if it's not empty.

**Comment by TimothyYe** [comment]
Hi, @khorsmann would pls help to check the output log of `godns`? I think this might be caused by failed to parse the notification template.

You may see something like `Failed to parse template` in the output log.

**Comment by khorsmann** [comment]
I filtered all skipped and 80.x.x.x.x ips out. 
Sometimes the website return nothing so that is what I got in the log 

root@rock:~# journalctl -t godns | grep -v 80 | grep -v sleep | grep -v Skip
-- Logs begin at Fri 2020-04-24 12:50:51 CEST, end at Sat 2020-05-02 17:33:20 CEST. --
Apr 26 22:49:09 rock godns[996]: [GoDNS] 2020/04/26 22:49:09 Cannot get IP...
Apr 26 22:49:09 rock godns[996]: [GoDNS] 2020/04/26 22:49:09 get ip online failed. Fallback to get ip from interface if possible.
Apr 26 22:49:09 rock godns[996]: [GoDNS] 2020/04/26 22:49:09 currentIP is:
Apr 26 22:49:10 rock godns[996]: [GoDNS] 2020/04/26 22:49:10 IP updated to:
May 01 15:10:08 rock godns[996]: [GoDNS] 2020/05/01 15:10:08 Cannot get IP...
May 01 15:10:08 rock godns[996]: [GoDNS] 2020/05/01 15:10:08 get ip online failed. Fallback to get ip from interface if possible.
May 01 15:10:08 rock godns[996]: [GoDNS] 2020/05/01 15:10:08 currentIP is:
May 01 15:10:19 rock godns[996]: [GoDNS] 2020/05/01 15:10:19 IP updated to:
May 01 19:11:34 rock godns[996]: [GoDNS] 2020/05/01 19:11:34 Cannot get IP...
May 01 19:11:34 rock godns[996]: [GoDNS] 2020/05/01 19:11:34 get ip online failed. Fallback to get ip from interface if possible.
May 01 19:11:34 rock godns[996]: [GoDNS] 2020/05/01 19:11:34 currentIP is:
May 01 19:11:35 rock godns[996]: [GoDNS] 2020/05/01 19:11:35 IP updated to:
May 01 19:21:53 rock godns[996]: [GoDNS] 2020/05/01 19:21:53 Cannot get IP...
May 01 19:21:53 rock godns[996]: [GoDNS] 2020/05/01 19:21:53 get ip online failed. Fallback to get ip from interface if possible.
May 01 19:21:53 rock godns[996]: [GoDNS] 2020/05/01 19:21:53 currentIP is:
May 01 19:21:54 rock godns[996]: [GoDNS] 2020/05/01 19:21:54 IP updated to:

**Comment by khorsmann** [comment]
So it gots sometimes "nothing"

**Comment by TimothyYe** [comment]
It seems the program failed to get IP from the internet and also failed to get IP from the interface.
Which provider do you use?
Can you share the configuration? You can simply remove your password and token.

**Comment by khorsmann** [comment]
@TimothyYe - sorry for the delay. I will try #67 today.

**Comment by khorsmann** [comment]
@TimothyYe - tried the latest stable version. V2.2
My System is an Armbian buster with Linux 4.4.213-rockchip64 on a SoC pine-rock64.
Runs native under systemd. Maybe the dhcpclient setting is crap?!

```shell
root@rock:/etc/network# cat /etc/network/interfaces.default
source /etc/network/interfaces.d/*
# Network is managed by Network manager
auto lo
iface lo inet loopback
```

```shell
root@rock:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether a6:c1:6b:96:f2:88 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.206/24 brd 192.168.2.255 scope global dynamic noprefixroute eth0
       valid_lft 2874sec preferred_lft 2874sec
    inet6 fe80::435e:f140:b5ac:a02c/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:1d:bd:2e:7d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by TimothyYe** [comment]
@khorsmann Try to run this command and check:
```bash
 curl https://myip.biturl.top
```
It should return your public IP

**Comment by khorsmann** [comment]
@TimothyYe 

curl returns my ip. and i use myip.biturl.top  (but its slow from my location, germany) - ifconfig.io is faster, but gets in trouble with ipv6 and ipv4 dualstack (or godns gets in trouble, so).

```json
{
  "provider": "DuckDNS",
  "password": "",
  "login_token": "SECRET_TOKEN",
  "domains": [
    {
      "domain_name": "duckdns.org",
      "sub_domains": [
        "somewheredomain"
      ]
    }
  ],
  "ip_url": "https://myip.biturl.top",
  "ipv6_url": "https://api-ipv6.ip.sb/ip",
  "interval": 300,
  "socks5_proxy": "",
  "notify": {
    "telegram": {
      "enabled": true,
      "bot_api_key": "SECRET_API_KEY",
      "chat_id": "SECRET_SOME_CHATID",
      "message_template": "Domain *{{ .Domain }}* is updated to %0A{{ .CurrentIP }}"
    }
  }
}
```

**Comment by khorsmann** [comment]
I will switch to ifconfig.io - and i build godns for my router directly. So maybe there i have more luck :-). Btw - its an OpenBSD 6.7 PCengines APU one. Build was easy 👍 

```json
{
  "provider": "DuckDNS",
  "password": "",
  "login_token": "SECRET_TOKEN",
  "domains": [
    {
      "domain_name": "duckdns.org",
      "sub_domains": [
        "somewheredomain"
      ]
    }
  ],
  "ip_url": "https://ifconfig.io/ip",
  "ipv6_url": "https://api-ipv6.ip.sb/ip",
  "interval": 300,
  "socks5_proxy": "",
  "notify": {
    "telegram": {
      "enabled": true,
      "bot_api_key": "SECRET_API_KEY",
      "chat_id": "SECRET_SOME_CHATID",
      "message_template": "Domain *{{ .Domain }}* is updated to %0A{{ .CurrentIP }}"
    }
  }
}
```

**Comment by TimothyYe** [comment]
@khorsmann The configuration looks good, still not sure why it sometimes cannot get the public IP.

**Comment by SadPencil** [comment]
@khorsmann, I wonder if your machine has more than one default routes.
The command to show all default routes, 
```bash
ip route list exact default
```

For example, on my machine, it looks like this:
>$ ip route list exact default
>none default via 192.168.1.1 dev eth0 proto unspec metric 0
>none default via 25.255.255.254 dev eth7 proto unspec metric 9999
So that I have two default routes, but the first route has the least metric, so all out-bound traffic should goes through 192.168.1.1.

curl handles multiple routes correctly, while the Go program might not.

**Comment by khorsmann** [comment]
I am using armbian on a rock64 soc and the command shows this up. 
root@rock:~# ip r list exact default
default via 192.168.2.1 dev eth0 proto static metric 100
