### ISSUE TITLE
multi-wan support

### ISSUE THREAD

**Issue by dreamer2q** [TimothyYe/godns#69]
I have four `WAN`s named from netwan1,netwan2...netwan4 which means I have 4 public ipv4 address and I want to dynamic dns all of them.

However, `godns` seems only support single `WAN` interface,

can `godns` support multi-wan?

**Comment by TimothyYe** [comment]
To support multi-wan, then we have to specify the relationship between public IP addresses and domains, for example:

when public IP1 changes, should update subdomain1.example.com
when public IP2 changes, should update subdomain2.example.com
etc...

It will make the logic more complex...

**Comment by dreamer2q** [comment]
As far as I can see, config pattern should be restructed in order to support such feature.

you can specify certain net interface to get the public ip and update the domain related to it.

**Comment by SadPencil** [comment]
Use multiple GoDNS config files and multiple GoDNS instances to meet the need.
Make both `ip_url` and `ipv6_url` empty. Specify the interface through `ip_interface`,

@TimothyYe Also, I found that, although Go's net library supports specifying which interface that sending HTTP request pass through, it won't actually succeed on a machine with multiple wan (multiple default routes, each one for a network card). If this strange behavior can't be fixed, (tbh, I can't find out why. The source code of Go's library looks all good, but the problem actually exists.) supporting multi-wan can only be achieved by only specifying `ip_interface` now.

**Comment by TimothyYe** [comment]
@SadPencil Thanks, I think to use multiple config files with multiple GoDNS instances is a good solution to this problem.
