### ISSUE TITLE
myip.biturl.top 这个出问题了，请问有替代的IP查询网址吗？

### ISSUE THREAD

**Issue by gzelvis** [TimothyYe/godns#72]
下午开始 myip.biturl.top 返回错误的IP，等了一个多小时还没恢复。请问有其它替代的查公网IP网址吗？否则godns用不起来。谢谢

**Comment by TimothyYe** [comment]
下午切换了DNS，现在应该已经恢复了吧？

**Comment by TimothyYe** [comment]
https://api.ip.sb/ip  这个也可以备用

**Comment by TimothyYe** [comment]
@gzelvis 我这边测试过了， https://myip.biturl.top/ 已经恢复了

**Comment by gzelvis** [comment]
我这里测试下来，今天 myip.biturl.top不断返回 162.158.179.114或者是172.68.253.135 这两个IP，那怕现在亦是如此，另一个你给的https://api.ip.sb/ip  无法连接

 

 

发件人: Timothy <notifications@github.com>
答复: TimothyYe/godns <reply@reply.github.com>
日期: 2020年6月17日 星期三 21:57
收件人: TimothyYe/godns <godns@noreply.github.com>
抄送: gzelvis <gzelvis@gmail.com>, Mention <mention@noreply.github.com>
主题: Re: [TimothyYe/godns] myip.biturl.top 这个出问题了，请问有替代的IP查询网址吗？ (#72)

 

@gzelvis 我这边测试过了， https://myip.biturl.top/ 已经恢复了

**Comment by gzelvis** [comment]
不好意思，的确是恢复了，是我的dns缓存的问题。谢谢你为我们带来了哪么好的软件

 

发件人: Timothy <notifications@github.com>
答复: TimothyYe/godns <reply@reply.github.com>
日期: 2020年6月17日 星期三 19:41
收件人: TimothyYe/godns <godns@noreply.github.com>
抄送: gzelvis <gzelvis@gmail.com>, Author <author@noreply.github.com>
主题: Re: [TimothyYe/godns] myip.biturl.top 这个出问题了，请问有替代的IP查询网址吗？ (#72)

 

https://api.ip.sb/ip 这个也可以备用
