### ISSUE TITLE
出现一个问题，求解答

### ISSUE THREAD

**Issue by zhzhyu** [TimothyYe/godns#79]
日志显示ip错误
![QQ截图20200826174945](https://user-images.githubusercontent.com/58381672/91289396-e16f5e80-e7c4-11ea-96ee-6dd866ea4500.jpg)
但实际上这个IP没问题，而且有时候就更新成功了，有时候就会这样显示
dns服务商为dnspod

**Comment by TimothyYe** [comment]
你是否启用了IPv6模式？
从日志来看是获取到的IPv6的地址，但解析域名的时候出错了，你的域名是否也设置成IPv6类型？
