### ISSUE TITLE
Less verbose option

### ISSUE THREAD

**Issue by Snack32** [TimothyYe/godns#90]
Would be possible to add a "less verbose" option in order to reduce the output to syslog (in case the ip does not change)? i.e., 

Actual output:
Jan 17 14:36:21 OMV godns[974]: [GoDNS] 2021/01/17 14:36:21 Current IP is: xx.xx.xx.xx
Jan 17 14:36:21 OMV godns[974]: [GoDNS] 2021/01/17 14:36:21 IP is the same as cached one. Skip update.
Jan 17 14:36:21 OMV godns[974]: [GoDNS] 2021/01/17 14:36:21 Going to sleep, will start next checking in 300 seconds...

Desired output:
Jan 17 14:36:21 OMV godns[974]: [GoDNS] 2021/01/17 14:36:21 IP is the same as cached one. Skip update.

In any case, thanks for your work!

**Comment by TimothyYe** [comment]
Thanks for your suggestion, I think this can be handled by different log levels, later I'll add the `log level` feature to support this.

**Comment by Snack32** [comment]
Thanks for your reply and time. 
Would be possible to add the current ip? ie.,:

Jan 17 14:36:21 OMV godns[974]: [GoDNS] 2021/01/17 14:36:21 IP is the same as cached one (xx.xx.xx.xx). Skip update.

Thanks!

**Comment by TimothyYe** [comment]
Sure.
