### ISSUE TITLE
Feature request: more format supporting for ip query result and continuation the ddns updating after the internet connection recovering after a failure.

### ISSUE THREAD

**Issue by hongyi-zhao** [TimothyYe/godns#92]
Currently, the godns has the following problems:

1. Query to the "ip_url" must only return the plain IP address, otherwise, the update process will fail. Could you please add more  format supporting for IP query result, say, JSON?
2. Godns won't continue to work if the internet connection recovering after a failure.

Regards,
HY

**Comment by TimothyYe** [comment]
1. I think plain IP is more common for the IP detecting APIs, to support IP query result with JSON format, different APIs may have different response formats, we have to make GoDNS parse different JSON responses.

2. Is there any errors or logs for this issue? It can help me to debug it.

**Comment by hongyi-zhao** [comment]
> Is there any errors or logs for this issue? It can help me to debug it.

It's just stuck there without any furthermore logs printing on the stdout.

**Comment by TimothyYe** [comment]
The second issue has been fixed, please get the latest version of GoDNS.
