### ISSUE TITLE
Docker Hub instructions are incorrect

### ISSUE THREAD

**Issue by shaworth** [TimothyYe/godns#97]
Recent [commit](https://github.com/TimothyYe/godns/commit/ac7dc021eb75f9d9f4ce6d4d42155605cdbbc5c4) moved the binary location in the docker container.  Instructions on DockerHub are incorrect.
## Change

`docker run -d --name godns --restart=always
-v /path/to/config.json:/usr/local/godns/config.json timothyye/godns:latest`

## To
`docker run -d --name godns --restart=always
-v /path/to/config.json:/config.json timothyye/godns:latest`

**Comment by TimothyYe** [comment]
Thanks, I updated the Dockerfile recently but forgot to update the Docker Hub instructions.

**Comment by TimothyYe** [comment]
Updated, thanks!
